# Generated by Django 4.1.2 on 2022-10-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USER_E',
            new_name='Us_E',
        ),
    ]
