# Generated by Django 4.1.2 on 2022-10-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamestat", "0003_rename_us_e_user_e"),
    ]

    operations = [
        migrations.DeleteModel(name="User_E",),
    ]
