

genre= (
    ('Action', "Action"),
    ('Adventure', "Adventure"),
    ('Fighting', "Fighting"), 
    ('Misc', 'Misc'),
    ('Platform', 'Platform'),
    ('Puzzle', 'Puzzle'),
    ('Racing', 'Racing'),
    ('Role-Playing', 'Role-Playing'),
    ('Shooter', 'Shooter'),
    ('Simulation', 'Simulation'),
    ('Sports', 'Sports'),
    ('Strategy', 'Strategy'),
    )

platform=(('2600','2600'),
 ('3DO','3DO'),
 ('3DS'),
 ('DC'),
 ('DS'),
 ('GB'),
 ('GBA'),
 ('GC'),
 ('GEN'),
 ('GG'),
 ('N64'),
 ('NES'),
 ('NG'),
 ('PC'),
 ('PCFX'),
 ('PS'),
 ('PS2'),
 ('PS3'),
 'PS4',
 ('PSP'),
 ('PSV'),
 ('SAT'),
 ('SCD'),
 ('SNES'),
 ('TG16'),
 ('WS'),
 ('Wii'),
 ('WiiU'),
 ('X360'),
 ('XB'),
 ('XOne'),
 )